{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mysql.serviceAccountName" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ template "mysql.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
secrets:
  - name: {{ template "mysql.secretName" . }}
  {{- end }}
